package matchwear.com.matchwearapp;

import java.net.FileNameMap;
import java.util.HashMap;
import java.util.HashSet;

/**
 * Created by ZP4 on 12/2/2016.
 */

public class Food {
    public HashMap<String, HashMap> American= new HashMap<String, HashMap>();
    public HashMap<String, HashMap> Brooklyn= new HashMap<String, HashMap>();
    public HashMap<String, HashMap> Southern_Comfort= new HashMap<String, HashMap>();
    public HashMap<String, HashMap> Hispanic= new HashMap<String, HashMap>();
    public HashMap<String, HashMap>Carribean = new HashMap<String ,HashMap>();
    public HashMap<String, HashMap> Europe  = new HashMap<String, HashMap>();
    public HashMap<String, HashMap> Middle_east= new HashMap<String, HashMap>();
    public HashMap<String, HashMap> Asia    = new HashMap<String, HashMap>();
    public HashMap<String, HashMap> Africa  = new HashMap<String, HashMap>();
    public HashMap<String, HashMap> Drinks  = new HashMap<String, HashMap>();

    public Food() {
        HashMap<String, HashMap> AA     = new HashMap<String, HashMap>();
        HashMap<String, String>FMNCB    = new HashMap<String,String>();
        FMNCB.put("Title", "Fried Mac N Cheese Balls");
        FMNCB.put("Description","Crispy balls filled with homemade mac n' cheese" );
        FMNCB.put("Price", "$29.99");
        FMNCB.put("Servings","20 pieces" );
        FMNCB.put("ID","USA01");
        HashMap<String, String>PCS      = new HashMap<String, String>();
        PCS.put("Title", "Philly Cheeseteak Sliders");
        PCS.put("Description", "Thinly sliced steak meat cooked with peppers and onions, and covered in provolone cheese");
        PCS.put("Price", "$45.99");
        PCS.put("Servings", "20 sandwiches");
        PCS.put("ID", "USA02");
        HashMap<String, String>NECCS    = new HashMap<String, String>();
        NECCS.put("Title", "New England Clam Chowder Soup");
        NECCS.put("Description", "A thick soup made with clams, onions, salt pork, potatoes, and milk");
        NECCS.put("Price", "$35.99");
        NECCS.put("Servings", "1 large bowl");
        NECCS.put("ID", "USA03");
        HashMap<String,HashMap>AE       = new HashMap<String, HashMap>();
        HashMap<String, String>SM       = new HashMap<String, String>();
        SM.put("Title", "Sliced Meatloaf");
        SM.put("Description", "Juicy carved meat loaf slices with a pour over tomato sauce");
        SM.put("Price", "$39.99");
        SM.put("Servings", "2-3 slices per person");
        SM.put("ID", "USE01");
        HashMap<String, String>CDRC     = new HashMap<String, String>();
        CDRC.put("Title", "Carved Double Roasted Chicken");
        CDRC.put("Description", "Carved roasted chicken marinated in rosemary and garlic  served with mushrooms and carrots");
        CDRC.put("Price", "$34.99");
        CDRC.put("Servings", "Whole chicken- precut");
        CDRC.put("ID", "USE02");
        HashMap<String, String>PCT      = new HashMap<String, String>();
        PCT.put("Title", "Paremsan Crusted Ttilapia");
        PCT.put("Description", "Garlic seasoned tilapia baked with shredded parmesan ");
        PCT.put("Price", "$34.99");
        PCT.put("Servings", "15 pieces");
        PCT.put("ID", "USE03");
        HashMap<String, HashMap>ASD     = new HashMap<String, HashMap>();
        HashMap<String, String>MP       = new HashMap<String, String>();
        MP.put("Title", "Mashed Potatoes");
        MP.put("Description","Buttery mashed potatoes that'll remind you of home ");
        MP.put("Price","$24.99");
        MP.put("Servings", "1 tray");
        MP.put("ID","USS01");
        HashMap<String, String>PS       = new HashMap<String, String>();
        PS.put("Title", "Potato Salad");
        PS.put("Description","Boiled potatoes dressed with olive oil, vinegar, finely minced parsley and garlic, hot chili peppers and salt");
        PS.put("Price","$20.99");
        PS.put("Servings", "1 large bowl");
        PS.put("ID","USS02");
        HashMap<String,String>SS        = new HashMap<String, String>();
        SS.put("Title", "Side Salad");
        SS.put("Description", "Salad included with croutons, shredded carrots, cucumbers and tomatoes served with choice of dressing");
        SS.put("Price", "$19.99");
        SS.put("Servings", "1 large bowl");
        SS.put("ID", "USS03");
        HashMap<String, HashMap>AD      = new HashMap<String, HashMap>();
        HashMap<String, String>AP       = new HashMap<String, String>();
        AP.put("Title", "Apple Pie");
        AP.put("Description", "fresh apples, mixed with the perfect blend of brown sugar and cinnamon");
        AP.put("Price", "$32.99");
        AP.put("Servings", "10 pieces");
        AP.put("ID", "USD01");
        HashMap<String, String>IC       = new HashMap<String, String>();
        IC.put("Title", "Ice Cream");
        IC.put("Description", "Comes in a variety of flavors; coconut, vanilla, lime , avocado, peanut, banana, and chocolate");
        IC.put("Price", "$24.99");
        IC.put("Servings", "10 bowls");
        IC.put("ID", "USD02");
        HashMap<String, String>RVC      = new HashMap<String, String>();
        RVC.put("Title", "Red Velvet Cupcakes");
        RVC.put("Description", "Fluffy, moist cupcakes with tangy cream cheese frosting heaped on top");
        RVC.put("Price", "$34.99");
        RVC.put("Servings", "10 cupcakes");
        RVC.put("ID", "USD03");


        AA.put("Fred Mac N Cheese Balls", FMNCB);
        AA.put("Philly Cheeseteak Sliders",PCS);
        AA.put("New England Clam Chowder Soup",NECCS);
        American.put("Appitizer", AA);
        AE.put("Sliced Meatloaf", SM);
        AE.put("Carved Double Roasted Chicken", CDRC);
        AE.put("Paremsan Crusted Ttilapia", PCT);
        American.put("Entrees", AE);
        ASD.put("Mashed Potatoes",MP);
        ASD.put("Potato Salad",PS);
        ASD.put("Side Salad",SS);
        American.put("Side Dish",ASD);
        AD.put("Apple Pie", AP);
        AD.put("Ice Cream", IC);
        AD.put("Red Velvet Cupcakes", RVC);
        American.put("Desserts", AD);

        HashMap<String, HashMap>BA      = new HashMap<String, HashMap>();
        HashMap<String, String>BP       = new HashMap<String, String>();
        BP.put("Title", "Bagel Pops");
        BP.put("Description", "Small bagel bites filled with cream cheese, and served on a stick");
        BP.put("Price", "$29.99");
        BP.put("Servings", "20 pieces");
        BP.put("ID", "BKA01");
        HashMap<String, String>CIHD     = new HashMap<String, String>();
        CIHD.put("Title", "Coney Island Hot Dog");
        CIHD.put("Description", "Iconic Coney Island hotdogs, topped with relish, deli mustard, chili and ketchup");
        CIHD.put("Price", "$29.99");
        CIHD.put("Servings", "10 pieces");
        CIHD.put("ID", "BKA02");
        HashMap<String, String>HW       = new HashMap<String, String>();
        HW.put("Title", "Hot Wings");
        HW.put("Description", "Cripsy boneless wings slathered in a flavor of your chocie and served with blue cheese");
        HW.put("Price", "$39.99");
        HW.put("Servings", "20 pieces");
        HW.put("ID", "BKA03");
        HashMap<String, HashMap>BE      = new HashMap<String, HashMap>();
        HashMap<String, String>BKB      = new HashMap<String, String>();
        BKB.put("Title", "BK Burger");
        BKB.put("Description", "Half pound beef burger with hot pastrami and melted swiss cheese, served with steak fries");
        BKB.put("Price", "$59.99");
        BKB.put("Servings", "10 pieces");
        BKB.put("ID", "BKE01");
        HashMap<String, String>PP       = new HashMap<String, String>();
        PP.put("Title", "Pulled Pork");
        PP.put("Description", "juicy pork is cooked carefully at low temperatures, steadily tenderizing the meat as it is seasoned carefully");
        PP.put("Price", "$49.99");
        PP.put("Servings", "15 pieces");
        PP.put("ID", "BKE02");
        HashMap<String, String>P        = new HashMap<String, String>();
        P.put("Title", "Pizza");
        P.put("Description", " A staple that consists of baked dough and marinara sauce, topped with melted mozzeralla");
        P.put("Price", "$59.99");
        P.put("Servings", "3 pies");
        P.put("ID", "BKE03");
        HashMap<String, HashMap>BSD     = new HashMap<String, HashMap>();
        HashMap<String, String>BWC      = new HashMap<String, String>();
        BWC.put("Title", "Bacon-Wrapped Crab");
        BWC.put("Description", "Juicy strips of crab wrapped with thin cut bacon");
        BWC.put("Price", "$39.99");
        BWC.put("Servings", "20 pieces");
        BWC.put("ID", "BKS01");
        HashMap<String, String>FC       = new HashMap<String, String>();
        FC.put("Title", "Fried Calamari");
        FC.put("Description", "Lightly fried Squid with a fresh marinara sauce");
        FC.put("Price", "$39.99");
        FC.put("Servings", "1 large tray");
        FC.put("ID", "BKS02");
        HashMap<String, String>MS       = new HashMap<String, String>();
        MS.put("Title", "Mozzarella Sticks");
        MS.put("Description", "Mozzarella sticks covered in bread crumbs and fried till golden brown");
        MS.put("Price", "$39.99");
        MS.put("Servings", "1 tray");
        MS.put("ID", "BKS03");
        HashMap<String, HashMap>BD      = new HashMap<String, HashMap>();
        HashMap<String, String>NYC      = new HashMap<String, String>();
        NYC.put("Title", "New York Cheesecake");
        NYC.put("Description", "Iconic New York Cheesecake");
        NYC.put("Price", "$49.99");
        NYC.put("Servings", "1 tray");
        NYC.put("ID", "BKD01");
        HashMap<String, String >IBC     = new HashMap<String, String>();
        IBC.put("Title", "Italian Bakery Canolis");
        IBC.put("Description", "Crisp, yet soft, cannoli shells filled with fresh cream");
        IBC.put("Price", "$59.99");
        IBC.put("Servings", "1 tray");
        IBC.put("ID", "BKD02");
        HashMap<String, String>CC       = new HashMap<String, String>();
        CC.put("Title", "Cotton Candy");
        CC.put("Description", "A light, very sweet candy of threaded sugar, often tinted with food coloring and twirled onto a stick");
        CC.put("Price", "$19.99");
        CC.put("Servings", "10 bags");
        CC.put("ID", "BKD03");
        


        BA.put("Bagel Pops", BP);
        BA.put("Coney Island Hot Dog", CIHD);
        BA.put("Hot Wings", HW);
        Brooklyn.put("Appitizer", BA);
        BE.put("BK Burger", BKB);
        BE.put("Pulled Pork", PP);
        BE.put("Pizza", P);
        Brooklyn.put("Entrees", BE);
        BSD.put("Bacon-Wrapped Crab",BWC);
        BSD.put("Fried Calamari", FC);
        BSD.put("Mozzarella Sticks", MS);
        Brooklyn.put("Side Dish",BSD);
        BD.put("New York Cheesecake",NYC);
        BD.put("Italian Bakery Canolis",IBC);
        BD.put("Cotton Candy",CC);
        Brooklyn.put("Desserts", BD);

        HashMap<String, HashMap>SCA     = new HashMap<String, HashMap>();
        HashMap<String, String>CFS      = new HashMap<String, String>();
        CFS.put("Title", "Cripsy Fried Shrimp");
        CFS.put("Description", "Beer battered shrimp deep fried and served with tartar sauce");
        CFS.put("Price", "$34.99");
        CFS.put("Servings", "30 pieces");
        CFS.put("ID", "SCA01");
        HashMap<String,String>CAWM      = new HashMap<String, String>();
        CAWM.put("Title", "Chicken and Waffle Minis");
        CAWM.put("Description", "Fried chicken pieces served over a mini waffle with a maple syrup drizzle");
        CAWM.put("Price", "$29.99");
        CAWM.put("Servings", "20 pieces");
        CAWM.put("ID", "SCA02");
        HashMap<String,String>HP        = new HashMap<String, String>();
        HP.put("Title", "Hushpuppies");
        HP.put("Description", "Small deep-fried balls made from cornmeal-based batter");
        HP.put("Price", "$37.99");
        HP.put("Servings", "20 pieces");
        HP.put("ID", "SCA03");
        HashMap<String, HashMap>SCE     = new HashMap<String, HashMap>();
        HashMap<String, String>CFSteak  = new HashMap<String, String>();
        CFSteak.put("Title", "Chicken Fried Steak");
        CFSteak.put("Description", "Pan fried steak cutlet coated with seasoned flour served with white gravy");
        CFSteak.put("Price", "$89.99");
        CFSteak.put("Servings", "10 Pieces");
        CFSteak.put("ID","SCE01");
        HashMap<String, String>BC      = new HashMap<String, String>();
        BC.put("Title", "Blackened Catfish");
        BC.put("Description", "Skillet cooked catfish seasoned with cajun spices ");
        BC.put("Price", "$84.99");
        BC.put("Servings", "15 Pieces");
        BC.put("ID","SCE02");
        HashMap<String, String>BPR      = new HashMap<String, String>();
        BPR.put("Title", "Barbeque Pork Ribs");
        BPR.put("Description", "Pork ribs grilled with a honey barbeque sauce (with bones and boneless)");
        BPR.put("Price", "$84.99 ");
        BPR.put("Servings", "20 Pieces");
        BPR.put("ID","SCE03");
        HashMap<String, HashMap>SCSD    = new HashMap<String, HashMap>();
        HashMap<String, String>SPF      = new HashMap<String, String>();
        SPF.put("Title", "Sweet Potato Fries");
        SPF.put("Description", "Air baked sweet potato fries seasoned with salt ");
        SPF.put("Price", "$24.99");
        SPF.put("Servings", "1 tray");
        SPF.put("ID","SCS01");
        HashMap<String, String>BBB      = new HashMap<String, String>();
        BBB.put("Title", "Barbeque Baked Beans");
        BBB.put("Description", "Slow cooked beans, simmered withbrown sugar, onion and barbeque sauce");
        BBB.put("Price", "$24.99");
        BBB.put("Servings", "1 tray");
        BBB.put("ID","SCS02");
        HashMap<String, String>BB      = new HashMap<String, String>();
        BB.put("Title", "Buttery Biscuits");
        BB.put("Description", "With a side of gravy");
        BB.put("Price", "$24.99");
        BB.put("Servings", "20 pieces");
        BB.put("ID","SCS03");
        HashMap<String, HashMap>SCD    = new HashMap<String, HashMap>();
        HashMap<String, String>UDC      = new HashMap<String, String>();
        UDC.put("Title", "Upside Down Cake");
        UDC.put("Description", "Cake made with blackberries, apples, and strawberries");
        UDC.put("Price", "$29.99");
        UDC.put("Servings", "10 pieces");
        UDC.put("ID","SCD01");
        HashMap<String, String>B      = new HashMap<String, String>();
        B.put("Title", "Beignets");
        B.put("Description", "a square deep-fried pastry served hot and sprinkled with icing sugar");
        B.put("Price", "$29.99");
        B.put("Servings", "20 pieces");
        B.put("ID","SCD02");
        HashMap<String, String>PC      = new HashMap<String, String>();
        PC.put("Title", "Peach Cobbler");
        PC.put("Description", "Peach Cobbler");
        PC.put("Price", "$34.99");
        PC.put("Servings", "10 pieces");
        PC.put("ID","SCD03");


        SCA.put("Cripsy Fried Shrimp", CFS);
        SCA.put("Chicken and Waffle Minis", CAWM);
        SCA.put("Hushpuppies",HP);
        Southern_Comfort.put("Appitizer", SCA);
        SCE.put("Chicken Fried Steak", CFSteak);
        SCE.put("Blackened Catfish", BC);
        SCE.put("Barbeque Pork Ribs",BPR);
        Southern_Comfort.put("Entrees",SCE);
        SCSD.put("Sweet Potato Fries",SPF);
        SCSD.put("Barbeque Baked Beans",BBB);
        SCSD.put("Buttery Biscuits",BB);
        Southern_Comfort.put("Side Dish",SCSD);
        SCD.put("Upside Down Cake",UDC);
        SCD.put("Beignets",B);
        SCD.put("Peach Cobbler",PC);
        Southern_Comfort.put("Desserts",SCD);

        HashMap<String, HashMap>HA     = new HashMap<String, HashMap>();
        HashMap<String, String>VT      = new HashMap<String, String>();
        VT.put("Title", "Vegan Tostones");
        VT.put("Description", "Fried savory plantains sprinkled with salt and served with a garlic and oil dipping sauce");
        VT.put("Price", "$29.99 ");
        VT.put("Servings", "20 pieces");
        VT.put("ID","HPA01");
        HashMap<String, String>SDM      = new HashMap<String, String>();
        SDM.put("Title", "Sorullitos de Maiz");
        SDM.put("Description", "Hush Puppies with a crunchy outer crust and a creamy buttery center");
        SDM.put("Price", "$29.99 ");
        SDM.put("Servings", "20 pieces");
        SDM.put("ID","HPA02");
        HashMap<String, String>S     = new HashMap<String, String>();
        S.put("Title", "Sancocho");
        S.put("Description", "Beef stew simmered with corn, potatoes, cilantro and onions");
        S.put("Price", "$39.99 ");
        S.put("Servings", "1 large bowl");
        S.put("ID","HPA03");
        HashMap<String, HashMap>HE   = new HashMap<String, HashMap>();
        HashMap<String, String>CM      = new HashMap<String, String>();
        CM.put("Title", "Chicken Mofongo");
        CM.put("Description", "Mashed plantains rounded into a bowl with seasoned chicken and vegetables inside");
        CM.put("Price", "$89.99");
        CM.put("Servings", "10 pieces");
        CM.put("ID","HPE01");
        HashMap<String, String>BCa      = new HashMap<String, String>();
        BCa.put("Title", "Beef Carnitas");
        BCa.put("Description", "Braised marinated steak in flour tortilla with cilantro and lime served with avocado  slices ");
        BCa.put("Price", "$89.99");
        BCa.put("Servings", "10 pieces");
        BCa.put("ID","HPE02");
        HashMap<String, String>SP      = new HashMap<String, String>();
        SP.put("Title", "Seafood Paella");
        SP.put("Description", "Rice cooked with shrimp, muscles, calamari and lobster pieces");
        SP.put("Price", "$89.99");
        SP.put("Servings", "1 tray");
        SP.put("ID","HPE03");
        HashMap<String , HashMap>HSD    = new HashMap<String, HashMap>();
        HashMap<String, String>ACG      = new HashMap<String, String>();
        ACG.put("Title", "Arroz con Gandules");
        ACG.put("Description", "Rice, pigeon peas and pork chunks, cooked with sofrito seasoning");
        ACG.put("Price", "$49.99 ");
        ACG.put("Servings", "1 tray");
        ACG.put("ID","HPS01");
        HashMap<String, String>Sa      = new HashMap<String, String>();
        Sa.put("Title", "Samosas");
        Sa.put("Description", "Fried dough stuffed with potatoes, peas, squash, and cauliflower served with mint chutney sauce");
        Sa.put("Price", "$34.99 ");
        Sa.put("Servings", "20 pieces");
        Sa.put("ID","HPS02");
        HashMap<String, String>Ba      = new HashMap<String, String>();
        Ba.put("Title", "Bacalaitos");
        Ba.put("Description", "Salted codfish pancake fritters");
        Ba.put("Price", "$39.99 ");
        Ba.put("Servings", "30 pieces");
        Ba.put("ID","HPS03");
        HashMap<String, HashMap>HD      = new HashMap<String, HashMap>();;
        HashMap<String, String>TL      = new HashMap<String, String>();
        TL.put("Title", "Tres Leche");
        TL.put("Description", "Sponge cake soaked in evaporated milk, condensed milk, and heavy cream");
        TL.put("Price", "$34.99 ");
        TL.put("Servings", "1 tray");
        TL.put("ID","HPD01");
        HashMap<String, String>C      = new HashMap<String, String>();
        C.put("Title", "Churros");
        C.put("Description", "Mini fried dough pastry sprinkled with cinnamon sugar");
        C.put("Price", "$19.99 ");
        C.put("Servings", "20 pieces");
        C.put("ID","HPD02");
        HashMap<String, String>SO      = new HashMap<String, String>();
        SO.put("Title", "Sopaipillas");
        SO.put("Description", "Light pastry puffs served with honey");
        SO.put("Price", "$29.99 ");
        SO.put("Servings", "20 pieces");
        SO.put("ID","HPD03");

        HA.put("Vegan Tostones",VT);
        HA.put("Sorullitos de Maiz",SDM);
        HA.put("Sancocho",S);
        Hispanic.put("Appitizer", HA);
        HE.put("Chicken Mofongo",CM);
        HE.put("Beef Carnitas",BCa);
        HE.put("Seafood Paella",SP);
        Hispanic.put("Entrees", HE);
        HSD.put("Arroz con Gandules",ACG);
        HSD.put("Samosas",Sa);
        HSD.put("Bacalaitos",Ba);
        Hispanic.put("Side Dish",HSD);
        HD.put("Tres Leche",TL);
        HD.put("Churros", C);
        HD.put("Sopaipillas", SO);
        Hispanic.put("Desserts",HD);

        //CARRIBEAN
        HashMap<String, HashMap>CAP   = new HashMap<String, HashMap>();
        HashMap<String, String>  BP1  = new HashMap<String, String>();
        BP1.put("Title", "Beef Patties");
        BP1.put("Description", "Meat patties filled with curried ground beef, onion, garlic, and Scotch bonnet pepper, plus a slew of aromatic herbs and spices");
        BP1.put("Price", "$29.99 ");
        BP1.put("Servings", "20 patties");
        BP1.put("ID","CBA01");
        HashMap<String, String> CF   = new HashMap<String, String>();
        CF.put("Title", "Callaloo Fritters");
        CF.put("Description", " green leaves,vegetables fried into a crispy proportion");
        CF.put("Price", "$34.99");
        CF.put("Servings", "1 large tray");
        CF.put("ID","CBA02");
        HashMap<String, String>  R = new HashMap<String, String>();
        R.put("Title", "Roti");
        R.put("Description", "flatbread crafted from stoneground wholemeal flour and wheat");
        R.put("Price", "$29.99");
        R.put("Servings", "10 pieces");
        R.put("ID","CBA03");
        HashMap<String, HashMap> CE   = new HashMap<String, HashMap>();
        HashMap<String, String> JO  = new HashMap<String, String>();
        JO.put("Title", "Jamaican Oxtail");
        JO.put("Description", "Oxtail mixed with onion, green onion, garlic, ginger, chile pepper, soy sauce, thyme, salt, and pepper");
        JO.put("Price", "$59.99 ");
        JO.put("Servings", "1 large tray ");
        JO.put("ID","CBE01");
        HashMap<String, String> JCYR  = new HashMap<String, String>();
        JCYR.put("Title", "Jerk Chicken with yellow rice");
        JCYR.put("Description", "Chicken dry-rubbed or wet marinated with a very hot Jamaican jerk spice");
        JCYR.put("Price", "$54.99 ");
        JCYR.put("Servings", "1 large tray");
        JCYR.put("ID","CBE02");
        HashMap<String, String> CSPSPS  = new HashMap<String, String>();
        CSPSPS.put("Title", "Caribbean Split Peas and Salted Pigtail Soup");
        CSPSPS.put("Description", "Pigtail mixed with split peas, onions, red and black pepper, ham served with rice");
        CSPSPS.put("Price", "$54.99");
        CSPSPS.put("Servings", "10 pieces");
        CSPSPS.put("ID","CBE03");
        HashMap<String, HashMap>  CSD  = new HashMap<String, HashMap>();
        HashMap<String, String> CB  = new HashMap<String, String>();
        CB.put("Title", "Cornbread");
        CB.put("Description", "Bread hand crafted in a batter made of wheat flour, cornmeal, milk or buttermilk, eggs, salt, and usually sugar");
        CB.put("Price", "$27.99");
        CB.put("Servings", "20 pieces");
        CB.put("ID","CBS01");
        HashMap<String, String>  PR = new HashMap<String, String>();
        PR.put("Title", "Peas and Rice");
        PR.put("Description", "Cajun flavored rice mixed with seasoned peas");
        PR.put("Price", "$34.99");
        PR.put("Servings", "1 tray");
        PR.put("ID","CBS02");
        HashMap<String, HashMap>  CD  = new HashMap<String, HashMap>();
        HashMap<String, String> CRC  = new HashMap<String, String>();
        CRC.put("Title", "Caribbean Rum Cake");
        CRC.put("Description", "Caramalized fruit soaked in rum flavored syrup and baked into a rich cake");
        CRC.put("Price", "$54.99 ");
        CRC.put("Servings", "1 tray");
        CRC.put("ID","CBD01");
        HashMap<String, String> BP2  = new HashMap<String, String>();
        BP2.put("Title", "Bread Pudding");
        BP2.put("Description", "Bread made from a mixture of cream, butter, eggs and caramalized into a pudding");
        BP2.put("Price", "$29.99");
        BP2.put("Servings", "1 tray");
        BP2.put("ID","CBD02");
        HashMap<String, String> PM  = new HashMap<String, String>();
        PM.put("Title", "Pineapple Marmalade");
        PM.put("Description", "Crushed pineapple with sugar,water and lemon");
        PM.put("Price", "$24.99 ");
        PM.put("Servings", "1 tray");
        PM.put("ID","CBD03");
        /*
        HashMap<String, HashMap>    = new HashMap<String, HashMap>();

        HashMap<String, String>   = new HashMap<String, String>();
        .put("Title", "");
        .put("Description", "");
        .put("Price", "");
        .put("Servings", "");
        .put("ID","");
         */

        CAP.put("Beef Patties", BP1);
        CAP.put("Callaloo Fritters", CF);
        CAP.put("Roti", R);
        CE.put("Jamaican Oxtail", JO);
        CE.put("Jerk Chicken with yellow rice", JCYR);
        CE.put("Caribbean Split Peas and Salted Pigtail Soup", CSPSPS);
        CSD.put("Cornbread",CB );
        CSD.put("Peas and Rice",PR );
        CD.put("Caribbean Rum Cake",CRC );
        CD.put("Bread Pudding", BP);
        CD.put("Pineapple Marmalade",PM );

        Carribean.put("Appetizer", CAP );
        Carribean.put("Entrees", CE);
        Carribean.put("Side Dishes",CSD );
        Carribean.put("Desserts",CD );

        //EUROPE
        HashMap<String, HashMap>EA  = new HashMap<String, HashMap>();
        HashMap<String, String>MPRB      = new HashMap<String, String>();
        MPRB.put("Title", "Mini Prosciutto Rice Balls");
        MPRB.put("Description", "Deep fried rice croquettes filled with prosciutto, provolone, and seasoned rice ");
        MPRB.put("Price", "$29.99 ");
        MPRB.put("Servings", "20 pieces");
        MPRB.put("ID","EUA01");
        HashMap<String, String>VSEC      = new HashMap<String, String>();
        VSEC.put("Title", "Vegan Spicy Eggplant Capanota");
        VSEC.put("Description", "Cooked vegetable salad with sauteed diced eggplant, tomatoes, and sweet white onions");
        VSEC.put("Price", "$34.99 ");
        VSEC.put("Servings", "1 tray");
        VSEC.put("ID","EUA02");
        HashMap<String, String>CG      = new HashMap<String, String>();
        CG.put("Title", "Cheddar Gougeres");
        CG.put("Description", "A baked savory choux pastry mixed with cheese.");
        CG.put("Price", "$24.99 ");
        CG.put("Servings", "20 pieces");
        CG.put("ID","EUA03");
        HashMap<String, String>PCA      = new HashMap<String, String>();
        PCA.put("Title", "Prawn Canapes");
        PCA.put("Description", "bite-sized shrimp grilled to a crispy golden brown");
        PCA.put("Price", "$34.99 ");
        PCA.put("Servings", "20 pieces");
        PCA.put("ID","EUA04");
        HashMap<String, String>PL     = new HashMap<String, String>();
        PL.put("Title", "Potato Latkes");
        PL.put("Description", "A potato pancake seasoned with breadcrumbs, garlic and marjoram");
        PL.put("Price", "$29.99 ");
        PL.put("Servings", "20 pieces");
        PL.put("ID","EUA05");
        HashMap<String,HashMap>EE      = new HashMap<String, HashMap>();
        HashMap<String, String>PAV      = new HashMap<String, String>();
        PAV.put("Title", "Penne ala Vodka");
        PAV.put("Description", "Al dente penne pasta with a creamy vodka sauce served with grilled chicken breast (does not contain alcohol)");
        PAV.put("Price", "$69.99 ");
        PAV.put("Servings", "1 tray");
        PAV.put("ID","EUE01");
        HashMap<String, String>UD      = new HashMap<String, String>();
        UD.put("Title", "Udoli Doma");
        UD.put("Description", "Stuffed vegetable dish that contains tomato, pepper, onion, zucchini, eggplant, and garlic. ");
        UD.put("Price", "$49.99 ");
        UD.put("Servings", "10 pieces");
        UD.put("ID","EUE02");
        HashMap<String, String>HBS      = new HashMap<String, String>();
        HBS.put("Title", "Halal Beef Souvlaki");
        HBS.put("Description", "Marinated beef cubes, grilled and served with pita bread");
        HBS.put("Price", "$59.99 ");
        HBS.put("Servings", "20 pieces");
        HBS.put("ID","EUE03");
        HashMap<String, String>HLGTS      = new HashMap<String, String>();
        HLGTS.put("Title", "Halal Lamb Gyro with Tzatziki Sauce");
        HLGTS.put("Description", " Grilled lamb cubes drizzled with tzatziki sauce, served in pita bread");
        HLGTS.put("Price", "$59.99 ");
        HLGTS.put("Servings", "10 pieces");
        HLGTS.put("ID","EUE04");
        HashMap<String, String>M      = new HashMap<String, String>();
        M.put("Title", "Maultaschen");
        M.put("Description", " Pasta dough filled with seasoned sausage and onions");
        M.put("Price", "$74.99 ");
        M.put("Servings", "20 pieces");
        M.put("ID","EUE05");
        HashMap<String, String>WS      = new HashMap<String, String>();
        WS.put("Title", "Wiener Schnitzel");
        WS.put("Description", "Breaded veal pan fried until golden brown, served with mashed potatoes");
        WS.put("Price", "$84.99 ");
        WS.put("Servings", "10 pieces");
        WS.put("ID","EUE06");
        HashMap<String, HashMap>ESD     = new HashMap<String, HashMap>();
        HashMap<String, String>VCS      = new HashMap<String, String>();
        VCS.put("Title", "Vegetarian Caprese Salad");
        VCS.put("Description", "Sliced tomato and mozzerlla, topped with basil and drizzeled with balsamic vinegar");
        VCS.put("Price", "$24.99 ");
        VCS.put("Servings", "1 tray");
        VCS.put("ID","EUS01");
        HashMap<String, String>PE      = new HashMap<String, String>();
        PE.put("Title", "Perogies");
        PE.put("Description", "Dumplings filled with potato and onions.");
        PE.put("Price", "$39.99 ");
        PE.put("Servings", "20 pieces");
        PE.put("ID","EUS02");
        HashMap<String, String>VGS      = new HashMap<String, String>();
        VGS.put("Title", "Vegetarian Greek Salad");
        VGS.put("Description", " Diced tomatoes, cucumbers, red onions, and feta combined with olive oil");
        VGS.put("Price", "$29.99 ");
        VGS.put("Servings", "1 large bowl");
        VGS.put("ID","EUS03");
        HashMap<String, String>A      = new HashMap<String, String>();
        A.put("Title", "Antipasta");
        A.put("Description", "Traditional antipasto that has meats, olives, mushrooms, anchovies, and artichoke hearts ");
        A.put("Price", "$44.99 ");
        A.put("Servings", "1 large tray");
        A.put("ID","EUS04");
        HashMap<String, String>SPA      = new HashMap<String, String>();
        SPA.put("Title", "Spanokopita ");
        SPA.put("Description", "Pastries filled with spinach and feta cheese.");
        SPA.put("Price", "$39.99 ");
        SPA.put("Servings", "10 pieces");
        SPA.put("ID","EUS05");
        HashMap<String, HashMap>ED      = new HashMap<String, HashMap>();
        HashMap<String, String>TC      = new HashMap<String, String>();
        TC.put("Title", "Tiramisu Cake");
        TC.put("Description", "Small buns made of yeasted dough topped with garlic.");
        TC.put("Price", "$29.99 ");
        TC.put("Servings", "1 tray");
        TC.put("ID","EUD01");
        HashMap<String, String>PA      = new HashMap<String, String>();
        PA.put("Title", "Pampushki");
        PA.put("Description", "Small buns made of yeasted dough topped with garlic.");
        PA.put("Price", "$29.99 ");
        PA.put("Servings", "10 pieces");
        PA.put("ID","EUD02");
        HashMap<String, String>MA      = new HashMap<String, String>();
        MA.put("Title", "Macaroons");
        MA.put("Description", "Small circular cakes with a variety of toppings.");
        MA.put("Price", "$39.99 ");
        MA.put("Servings", "20 pieces");
        MA.put("ID","EUD03");

        EA.put("Mini Prosciutto Rice Balls",MPRB);
        EA.put("Vegan Spicy Eggplant Capanota",VSEC);
        EA.put("Cheddar Gougeres",CG);
        EA.put("Prawn Canapes",PCA);
        EA.put("Potato Latkes",PL);
        Europe.put("Appitizer", EA);
        EE.put("Penne ala Vodka",PAV);
        EE.put("Udoli Doma", UD);
        EE.put("Halal Beef Souvlaki",HBS);
        EE.put("Halal Lamb Gyro with Tzatziki Sauce",HLGTS);
        EE.put("Maultaschen",M);
        EE.put("Wiener Schnitzel",WS);
        Europe.put("Entrees", EE);
        ESD.put("Vegetarian Caprese Salad",VCS);
        ESD.put("Perogies",PE);
        ESD.put("Vegetarian Greek Salad",VGS);
        ESD.put("Antipasta",A);
        ESD.put("Spanokopita",SPA);
        Europe.put("Side Dish",ESD);
        ED.put("Tiramisu Cake",TC);
        ED.put("Pampushki",PA);
        ED.put("Macaroons",MA);
        Europe.put("Desserts",ED);


        HashMap<String, HashMap>MEA     = new HashMap<String, HashMap>();
        HashMap<String, String>VBGP      = new HashMap<String, String>();
        VBGP.put("Title", "Vegan Baba Ghanoush & Pita");
        VBGP.put("Description", "Cooked eggplant mixed with onions, tomatoes, olive oil, served with pita slices");
        VBGP.put("Price", "$29.99 ");
        VBGP.put("Servings", "1 large bowl");
        VBGP.put("ID","MAA01");
        HashMap<String, String>SA      = new HashMap<String, String>();
        SA.put("Title", "Sambosas");
        SA.put("Description", "Minced meat with chopped red onion wonton which is slightly fried. ");
        SA.put("Price", "$39.99 ");
        SA.put("Servings", "10 pieces");
        SA.put("ID","MAA02");
        HashMap<String, String>FM      = new HashMap<String, String>();
        FM.put("Title", "Falafel Minis");
        FM.put("Description", "Small croquette's made from ground chick peas, seasoned with toasted sesame seeds and salt");
        FM.put("Price", "$44.99 ");
        FM.put("Servings", "40 pieces");
        FM.put("ID","MAA03");
        HashMap<String, HashMap>MEE     = new HashMap<String, HashMap>();
        HashMap<String, String>HPBK      = new HashMap<String, String>();
        HPBK.put("Title", "Halal Pepper & Beef Kabobs");
        HPBK.put("Description", "Sirloin steak chunks skewered with red and yellow bell peppers ang seared to perfection");
        HPBK.put("Price", "$59.99 ");
        HPBK.put("Servings", "20 pieces");
        HPBK.put("ID","MAE01");
        HashMap<String, String>HLS      = new HashMap<String, String>();
        HLS.put("Title", "Halal Lamb Shawarma");
        HLS.put("Description", "Sliced lamb stuffed in pita with tahini sauce, cucumbers and tomatoes");
        HLS.put("Price", "$74.99 ");
        HLS.put("Servings", "10 pieces");
        HLS.put("ID","MAE02");
        HashMap<String, String>CT      = new HashMap<String, String>();
        CT.put("Title", "Chicken Tandoori");
        CT.put("Description", "Chicken marinated in yogurt and seasoned with cayenne pepper and red chilli powder.");
        CT.put("Price", "$59.99 ");
        CT.put("Servings", "1 tray");
        CT.put("ID","MAE03");
        HashMap<String, HashMap>MESD    = new HashMap<String, HashMap>();
        HashMap<String, String>VSP      = new HashMap<String, String>();
        VSP.put("Title", "Vegetarian Spinach Pies");
        VSP.put("Description", "Spinach mixed with lemon and sumac, stuffed in a puffed pastry");
        VSP.put("Price", "$44.99 ");
        VSP.put("Servings", "10 pieces");
        VSP.put("ID","MAS01");
        HashMap<String, String>VTS      = new HashMap<String, String>();
        VTS.put("Title", "Vegan Tabbouleh Salad");
        VTS.put("Description", "Salad made of tomatoes, finely chopped parsley, mint and bulgur");
        VTS.put("Price", "$39.99 ");
        VTS.put("Servings", "1 tray");
        VTS.put("ID","MAS02");
        HashMap<String, String>VC      = new HashMap<String, String>();
        VC.put("Title", "Vegetarian Couscous");
        VC.put("Description", "Granular semolina moistened with water, lightly covered in flour, and rolled into tiny beadlike pellets");
        VC.put("Price", "$44.99 ");
        VC.put("Servings", "1 tray");
        VC.put("ID","MAS03");
        HashMap<String , HashMap>MED    = new HashMap<String, HashMap>();
        HashMap<String, String>AW      = new HashMap<String, String>();
        AW.put("Title", "Awameh");
        AW.put("Description", "A deep-fried pastry made of honey soaked dough");
        AW.put("Price", "$24.99 ");
        AW.put("Servings", "10 pieces");
        AW.put("ID","MAD01");
        HashMap<String, String>BAK      = new HashMap<String, String>();
        BAK.put("Title", "Baklava");
        BAK.put("Description", "Phyllo pastry filled with chopped pistachios and soaked in honey");
        BAK.put("Price", "$44.99 ");
        BAK.put("Servings", "1 tray");
        BAK.put("ID","MAD02");
        HashMap<String, String>BAS      = new HashMap<String, String>();
        BAS.put("Title", "Basboussa");
        BAS.put("Description", "Cooked semolina served in a sweet syrup sprinkled with chopped almonds ");
        BAS.put("Price", "$39.99 ");
        BAS.put("Servings", "1 tray");
        BAS.put("ID","MAD03");

        MEA.put("Vegan Baba Ghanoush & Pita",VBGP);
        MEA.put("Sambosas",SA);
        MEA.put("Falafel Minis",FM);
        Middle_east.put("Appitizer",MEA);
        MEE.put("Halal Pepper & Beef Kabobs",HPBK);
        MEE.put("Halal Lamb Shawarma",HLS);
        MEE.put("Chicken Tandoori",CT);
        Middle_east.put("Entrees", MEE);
        MESD.put("Vegetarian Spinach Pies",VSP);
        MESD.put("Vegan Tabbouleh Salad",VTS);
        MESD.put("Vegetarian Couscous",VC);
        Middle_east.put("Side Dish",MESD);
        MED.put("Awameh",AW);
        MED.put("Baklava",BAK);
        MED.put("Basboussa",BAS);
        Middle_east.put("Desserts",MED);

        HashMap<String , HashMap>ASA    = new HashMap<String, HashMap>();
        HashMap<String, String>SR      = new HashMap<String, String>();
        SR.put("Title", "Summer Rolls");
        SR.put("Description", " cooked shrimp, rice noodles, and plenty of fresh herbs and vegetables for flavor and crunch wrapped with rice paper wrappers");
        SR.put("Price", "$39.99 ");
        SR.put("Servings", "10 rolls");
        SR.put("ID","AAA01");
        HashMap<String, String>TM      = new HashMap<String, String>();
        TM.put("Title", "Taiwanese Meatballs");
        TM.put("Description", "pork with the mixture of bamboo shoots and shiitake mushrooms and it's served drenched in a sweet chili sauce");
        TM.put("Price", "$34.99 ");
        TM.put("Servings", "10 meatballs");
        TM.put("ID","AAA02");
        HashMap<String, String>ST      = new HashMap<String, String>();
        ST.put("Title", "Shrimp Tempura");
        ST.put("Description", " Shrimp delicately marinated in a simple tempura batter, then deep fried");
        ST.put("Price", "$44.99");
        ST.put("Servings", "30 pieces");
        ST.put("ID","AAA03");
        HashMap<String, String>BN      = new HashMap<String, String>();
        BN.put("Title", "Beef Negimaki");
        BN.put("Description", " Broiled strips of beef marinated in teriyaki sauce and rolled with scallions  ");
        BN.put("Price", "$44.99 ");
        BN.put("Servings", "20 pieces");
        BN.put("ID","AAA04");
        HashMap<String, String>KD      = new HashMap<String, String>();
        KD.put("Title", "Kimchi Dumplings");
        KD.put("Description", "Steamed soft dumplings filled with spicy kimchi");
        KD.put("Price", "$29.99 ");
        KD.put("Servings", "20 pieces");
        KD.put("ID","AAA05");
        HashMap<String, String>CER      = new HashMap<String, String>();
        CER.put("Title", "Chicken Egg Rolls");
        CER.put("Description", "deep-fried cylindrical casing of thin egg dough, filled with minced vegetables and meat");
        CER.put("Price", "$29.99 ");
        CER.put("Servings", "10 egg rolls");
        CER.put("ID","AAA06");
        HashMap<String, HashMap>ASE     = new HashMap<String, HashMap>();
        HashMap<String, String>SPT      = new HashMap<String, String>();
        SPT.put("Title", "Shrimp Pad Thai");
        SPT.put("Description", "Stir fried rice noodles with eggs shrimp, garlic, red pepper and lime");
        SPT.put("Price", "$64.99 ");
        SPT.put("Servings", "1 large tray");
        SPT.put("ID","AAE01");
        HashMap<String, String>VVMS      = new HashMap<String, String>();
        VVMS.put("Title", "Vegan Vegetable Mu Shu");
        VVMS.put("Description", "Thick noodles stir fried in sesame oil with wood ear mushrooms, cabbage, broccoli and scallions ");
        VVMS.put("Price", "$59.99 ");
        VVMS.put("Servings", "1 large tray");
        VVMS.put("ID","AAE02");
        HashMap<String, String>SST      = new HashMap<String, String>();
        SST.put("Title", "Sesame Seared Tuna");
        SST.put("Description", "Fresh tuna pan seared with sesame seeds, served rare");
        SST.put("Price", "$79.99 ");
        SST.put("Servings", "10 pieces");
        SST.put("ID","AAE03");
        HashMap<String, String>BT      = new HashMap<String, String>();
        BT.put("Title", "Beef Teryiaki");
        BT.put("Description", "Slicded-browned beef sirloin strips and broccoli florets; simmered in a soy sauce and garlic");
        BT.put("Price", "$79.99 ");
        BT.put("Servings", "1 tray");
        BT.put("ID","AAE04");
        HashMap<String, String>BU      = new HashMap<String, String>();
        BU.put("Title", "Bulgogi");
        BU.put("Description", " Thinly sliced or shredded beef marinated in soy sauce, sesame oil, garlic, sugar, scallions, and black pepper, cooked on a grill");
        BU.put("Price", "$79.99 ");
        BU.put("Servings", "1 tray");
        BU.put("ID","AAE05");
        HashMap<String, String>DG      = new HashMap<String, String>();
        DG.put("Title", "Dak Galbi");
        DG.put("Description", " Stir-fry marinated diced chicken in a gochujang based sauce, and sliced cabbage, sweet potato, scallions, onions and tteok");
        DG.put("Price", "$69.99 ");
        DG.put("Servings", "1 tray");
        DG.put("ID","AAE06");
        HashMap<String, HashMap>ASSD    = new HashMap<String, HashMap>();
        HashMap<String, String>LP      = new HashMap<String, String>();
        LP.put("Title", "Lemongrass Peas");
        LP.put("Description", " Tangy lime and lemongrass served with rice and fried fish.");
        LP.put("Price", "$39.99 ");
        LP.put("Servings", "1 large bowl");
        LP.put("ID","AAS01");
        HashMap<String, String>UN      = new HashMap<String, String>();
        UN.put("Title", "Udon Noodles");
        UN.put("Description", "Thick noodle made with wheat flour, served in soup");
        UN.put("Price", "$49.99 ");
        UN.put("Servings", "1 large tray");
        UN.put("ID","AAS02");
        HashMap<String, String>EDS      = new HashMap<String, String>();
        EDS.put("Title", "Egg Drop Soup");
        EDS.put("Description", " Soup with chicken broth, green onions, and seasonings");
        EDS.put("Price", "$39.99 ");
        EDS.put("Servings", "1 large bowl");
        EDS.put("ID","AAS03");
        HashMap<String, String>SGB      = new HashMap<String, String>();
        SGB.put("Title", "Sesame Green Beans");
        SGB.put("Description", "Green beans stir fried in sesame oil and topped with roasted sesame seeds");
        SGB.put("Price", "$34.99 ");
        SGB.put("Servings", "1 tray");
        SGB.put("ID","AAS04");
        HashMap<String, String>K      = new HashMap<String, String>();
        K.put("Title", "Kimchi");
        K.put("Description", "Fermented napa cabbage spiced with chili paste and chili flakes");
        K.put("Price", "$29.99 ");
        K.put("Servings", "1 tray");
        K.put("ID","AAS05");
        HashMap<String, String>KO      = new HashMap<String, String>();
        KO.put("Title", "Kongnamul");
        KO.put("Description", "Cold boiled bean sprouts with sesame oil");
        KO.put("Price", "$29.99 ");
        KO.put("Servings", "10 pieces");
        KO.put("ID","AAS06");
        HashMap<String,HashMap>ASID      = new HashMap<String, HashMap>();
        HashMap<String, String>SC      = new HashMap<String, String>();
        SC.put("Title", "5-Spice Cake");
        SC.put("Description", "caramel ginger ice cream and a berry compote");
        SC.put("Price", "$35.99 ");
        SC.put("Servings", "10 pieces");
        SC.put("ID","AAD01");
        HashMap<String, String>CMO      = new HashMap<String, String>();
        CMO.put("Title", "Chocolate Mochi");
        CMO.put("Description", "Pounded sticky rice with chocolate ice cream filling");
        CMO.put("Price", "$29.99 ");
        CMO.put("Servings", "20 pieces");
        CMO.put("ID","AAD02");
        HashMap<String, String>CCO      = new HashMap<String, String>();
        CCO.put("Title", "Chestnut Cookies");
        CCO.put("Description", "Vanilla cookies flavored with chestnuts");
        CCO.put("Price", "$19.99 ");
        CCO.put("Servings", "20 pieces");
        CCO.put("ID","AAD03");

        ASA.put("Summer Rolls",SR);
        ASA.put("Taiwanese Meatballs",TM);
        ASA.put("Shrimp Tempura",ST);
        ASA.put("Beef Negimaki",BN);
        ASA.put("Kimchi Dumplings",KD);
        ASA.put("Chicken Egg Rolls",CER);
        Asia.put("Appitizer",ASA);
        ASE.put("Shrimp Pad Thai",SPT);
        ASE.put("Vegan Vegetable Mu Shu",VVMS);
        ASE.put("Sesame Seared Tuna",SST);
        ASE.put("Beef Teryiaki", BT);
        ASE.put("Bulgogi", BU);
        ASE.put("Dak Galbi", DG);
        Asia.put("Entrees",ASE);
        ASSD.put("Lemongrass Peas",LP);
        ASSD.put("Udon Noodles",UN);
        ASSD.put("Egg Drop Soup",EDS);
        ASSD.put("Sesame Green Beans",SGB);
        ASSD.put("Kimchi",K);
        ASSD.put("Kongnamul",KO);
        Asia.put("Side Dish",ASSD);
        ASID.put("5-Spice Cake",SC);
        ASID.put("Chocolate Mochi",CMO);
        ASID.put("Chestnut Cookies",CCO);
        Asia.put("Desserts",ASID);

        HashMap<String, HashMap>AFA =new HashMap<String, HashMap>();
        HashMap<String, String>PSO      = new HashMap<String, String>();
        PSO.put("Title", "Pepper Soup");
        PSO.put("Description", "Chicken broth with heavy cream, peppers, onion");
        PSO.put("Price", "$49.99 ");
        PSO.put("Servings", "5 bowls");
        PSO.put("ID","AFA01");
        HashMap<String, String>PPU      = new HashMap<String, String>();
        PPU.put("Title", "Puff Puff");
        PPU.put("Description", " dough containing flour, yeast, sugar, butter, salt, water and eggs and deep fried in vegetable oil");
        PPU.put("Price", "$29.99 ");
        PPU.put("Servings", "20 pieces");
        PPU.put("ID","AFA02");
        HashMap<String, HashMap>AFE = new HashMap<String, HashMap>();
        HashMap<String, String>EWE      = new HashMap<String, String>();
        EWE.put("Title", "Eba with egusi ");
        EWE.put("Description", "Melon seeds, cut of cow meat (shaki), dry fish, seasoned with pepper and salt");
        EWE.put("Price", "$59.99 ");
        EWE.put("Servings", "1 large tray");
        EWE.put("ID","AFE01");
        HashMap<String, String>RFS      = new HashMap<String, String>();
        RFS.put("Title", "Rice with fish and soup ");
        RFS.put("Description", "Fish broth with chopped vegetables, soy sauce, vinegar");
        RFS.put("Price", "$54.99 ");
        RFS.put("Servings", "1 tray");
        RFS.put("ID","AFE02");
        HashMap<String, HashMap>AFSD    = new HashMap<String, HashMap>();
        HashMap<String, String>MMO      = new HashMap<String, String>();
        MMO.put("Title", "Mixed Meat and Okra");
        MMO.put("Description", "Beef, chicken and turkey in a Liberian okra sauce.");
        MMO.put("Price", "$40.99 ");
        MMO.put("Servings", "1 tray ");
        MMO.put("ID","AFS01");
        HashMap<String, String>SY      = new HashMap<String, String>();
        SY.put("Title", "Sweet Yams");
        SY.put("Description", "Sweet Yams cut into pieces and fried until crispy and added with toppings");
        SY.put("Price", "$29.99 ");
        SY.put("Servings", "1 tray");
        SY.put("ID","AFS02");
        HashMap<String, HashMap>AFD  = new HashMap<String, HashMap>();
        HashMap<String, String>ME      = new HashMap<String, String>();
        ME.put("Title", "Melktert");
        ME.put("Description", "Creamy milk tart in a pastry shell and topped with cinnamon");
        ME.put("Price", "$44.99 ");
        ME.put("Servings", "1 tray");
        ME.put("ID","AFD01");
        HashMap<String, String>KOE      = new HashMap<String, String>();
        KOE.put("Title", "Koeksisters");
        KOE.put("Description", "Braided fried dough served in a sweet syrup");
        KOE.put("Price", "$49.99 ");
        KOE.put("Servings", "20 pieces");
        KOE.put("ID","AFD02");

        AFA.put("Pepper Soup",PSO);
        AFA.put("Puff Puff",PPU);
        Africa.put("Appitizer",AFA);
        AFE.put("Eba with egusi",EWE);
        AFE.put("Rice with fish and soup",RFS);
        Africa.put("Entrees",AFE);
        AFSD.put("Mixed Meat and Okra",MMO);
        AFSD.put("Sweet Yams",SY);
        Africa.put("Side Dish",AFSD);
        AFD.put("Melktert",ME);
        AFD.put("Koeksisters",KOE);
        Africa.put("Desserts",AFD);

        HashMap<String, String>COCO      = new HashMap<String, String>();
        COCO.put("Title", "Coca Cola");
        COCO.put("Price", "$6.50 ");
        COCO.put("ID","BBB01");
        HashMap<String, String>DC      = new HashMap<String, String>();
        DC.put("Title", "Diet Coke");
        DC.put("Price", "$6.50 ");
        DC.put("ID","BBB02");
        HashMap<String, String>SPR      = new HashMap<String, String>();
        SPR.put("Title", "Sprite");
        SPR.put("Price", "$6.50");
        SPR.put("ID","BBB03");
        HashMap<String, String>F      = new HashMap<String, String>();
        F.put("Title", "Fanta");
        F.put("Price", "$6.50 ");
        F.put("ID","BBB04");
        HashMap<String, String>RB      = new HashMap<String, String>();
        RB.put("Title", "Root Beer");
        RB.put("Price", "$6.50 ");
        RB.put("ID","BBB05");
        HashMap<String, String>FR      = new HashMap<String, String>();
        FR.put("Title", "Fresca");
        FR.put("Price", "$6.50 ");
        FR.put("ID","BBB06");
        HashMap<String, String>GA      = new HashMap<String, String>();
        GA.put("Title", "Seagram's Ginger Ale");
        GA.put("Price", "$6.50 ");
        GA.put("ID","BBB07");
        HashMap<String, String>HT      = new HashMap<String, String>();
        HT.put("Title", "Honest Tea");
        HT.put("Price", "$6.50 ");
        HT.put("ID","BBB08");
        HashMap<String, String>PO      = new HashMap<String, String>();
        PO.put("Title", "Powerade");
        PO.put("Price", "$7.00 ");
        PO.put("ID","BBB09");
        HashMap<String, String>BW      = new HashMap<String, String>();
        BW.put("Title", "Bottled Water");
        BW.put("Price", "$5.50 ");
        BW.put("ID","BBB10");
        HashMap<String, String>CJ      = new HashMap<String, String>();
        CJ.put("Title", "Cranberry Juice");
        CJ.put("Price", "$7.00 ");
        CJ.put("ID","BBB11");
        HashMap<String, String>SOJ      = new HashMap<String, String>();
        SOJ.put("Title", "Simply Orange");
        SOJ.put("Price", "$7.00 ");
        SOJ.put("ID","BBB12");
        HashMap<String, String>AJ      = new HashMap<String, String>();
        AJ.put("Title", "Apple Juice");
        AJ.put("Price", "$7.00 ");
        AJ.put("ID","BBB13");

        Drinks.put("Coca Cola", COCO);
        Drinks.put("Diet Coke",DC);
        Drinks.put("Sprite",SPR);
        Drinks.put("Fanta",F);
        Drinks.put("Root Beer",RB);
        Drinks.put("Fresca",FR);
        Drinks.put("Seagram's Ginger Ale",GA);
        Drinks.put("Honest Tea",HT);
        Drinks.put("Powerade",PO);
        Drinks.put("Bottled Water",BW);
        Drinks.put("Cranberry Juice",CJ);
        Drinks.put("Simply Orange",SOJ);
        Drinks.put("Apple Juice",AJ);








        /*
        HashMap<String, String>      = new HashMap<String, String>();
        .put("Title", "");
        .put("Description", "");
        .put("Price", "");
        .put("Servings", "");
        .put("ID","");
         */

    }
}
